### ISSUE TITLE
Please update the data abstractions table

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Design#2]
@eiriktsarpalis - could you update [this table](https://github.com/mbraceproject/MBrace.Design/blob/master/DataAbstractions.md) after the recent additions and/or design changes?

**Comment by eiriktsarpalis** [comment]
Yes, it's on my todo list as soon as some core issues are sorted out.

**Comment by dsyme** [comment]
great

**Comment by eiriktsarpalis** [comment]
I just updated the table. This reflects the changes in the newly release core v0.9.10 but it hasn't appeared in any azure releases yet.
